# Generated by Django 5.2.17 on 2026-09-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.taxonomycategory')),
            ],
            options={
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='taxonomy.taxonomycategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.taxonomyattribute')),
            ],
            options={
                'ordering': ['value'],
                'indexes': [models.Index(fields=['attribute', 'value'], name='taxonomy_ta_attribu_65164b_idx'), models.Index(fields=['external_id'], name='taxonomy_ta_externa_643181_idx')],
                'constraints': [models.UniqueConstraint(fields=('attribute', 'value'), name='unique_value_per_attribute')],
            },
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['parent'], name='taxonomy_ta_parent__7393a3_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['name'], name='taxonomy_ta_name_06666d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyattribute',
            index=models.Index(fields=['category', 'name'], name='taxonomy_ta_categor_6077af_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomyattribute',
            index=models.Index(fields=['external_id'], name='taxonomy_ta_externa_42d73c_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxonomyattribute',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_attribute_name_per_category'),
        ),
    ]
