# Generated by Django 5.2.17 on 2026-09-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('classification_method', models.CharField(blank=True, choices=[('rule', 'Rule'), ('ai', 'AI'), ('hybrid', 'Hybrid'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('classified', 'Classified'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('needs_manual_review', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_results', to='taxonomy.taxonomycategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_result', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('rank', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_alternatives', to='taxonomy.taxonomycategory')),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='classification.classificationresult')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='started', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_attempts', to='products.product')),
            ],
            options={
                'ordering': ['product', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('ai', 'AI'), ('manual', 'Manual')], default='rule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='taxonomy.taxonomyattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['category', 'status'], name='classificat_categor_68fa13_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationalternative',
            index=models.Index(fields=['classification_result', 'rank'], name='classificat_classif_4e4094_idx'),
        ),
        migrations.AddConstraint(
            model_name='classificationalternative',
            constraint=models.UniqueConstraint(fields=('classification_result', 'rank'), name='unique_alternative_rank'),
        ),
        migrations.AddConstraint(
            model_name='classificationalternative',
            constraint=models.UniqueConstraint(fields=('classification_result', 'category'), name='unique_alternative_category'),
        ),
        migrations.AddIndex(
            model_name='processingattempt',
            index=models.Index(fields=['product', 'status'], name='classificat_product_299cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingattempt',
            constraint=models.UniqueConstraint(fields=('product', 'attempt_number'), name='unique_attempt_number_per_product'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product', 'attribute'], name='classificat_product_722188_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['attribute', 'value'], name='classificat_attribu_b8a82c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='unique_attribute_per_product'),
        ),
    ]
