# Generated by Django 5.2.17 on 2026-09-15 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], db_index=True, default='pending', max_length=30)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('processed_products', models.PositiveIntegerField(default=0)),
                ('successful_products', models.PositiveIntegerField(default=0)),
                ('failed_products', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('product_category', models.CharField(blank=True, max_length=255)),
                ('product_sub_category', models.CharField(blank=True, max_length=255)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('color_collection', models.CharField(blank=True, max_length=255)),
                ('product_color', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_description', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('set_includes', models.TextField(blank=True)),
                ('product_weight', models.CharField(blank=True, max_length=100)),
                ('materials', models.TextField(blank=True)),
                ('product_dimensions', models.CharField(blank=True, max_length=255)),
                ('assembly_required', models.BooleanField(blank=True, null=True)),
                ('is_set', models.BooleanField(blank=True, null=True)),
                ('stackable', models.BooleanField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('map', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_method', models.CharField(blank=True, max_length=255)),
                ('total_box_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pallet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_weight', models.CharField(blank=True, max_length=100)),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('package_dimensions', models.CharField(blank=True, max_length=255)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.importbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['product', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['import_batch', 'product_category'], name='products_pr_import__761ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='products_pr_product_1e41d2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model_number'], name='products_pr_model_n_80d291_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('import_batch', 'product_number'), name='unique_product_number_per_batch'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'position'], name='products_pr_product_78e37c_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_valid'], name='products_pr_is_vali_ef1a54_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'position'), name='unique_image_position_per_product'),
        ),
    ]
