# Generated by Django 5.2.17 on 2026-09-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dimensions',
            field=models.TextField(blank=True),
        ),
    ]
